# Generated by Django 5.1.4 on 2025-01-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer_name',
        ),
    ]
