# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_delivery_time',
            field=models.IntegerField(blank=True, help_text='Maximum delivery time in days', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
