# Generated by Django 5.1.4 on 2025-01-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0002_remove_businessprofile_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_ptr',
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
