# Generated by Django 5.1.4 on 2025-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0003_remove_customerprofile_profile_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
