# Generated by Django 5.1.4 on 2024-12-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0003_remove_offer_max_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
    ]
