# Generated by Django 5.1.4 on 2024-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0004_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
