# Generated by Django 5.1.4 on 2025-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0005_remove_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
