# Generated by Django 5.1.4 on 2024-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0006_remove_offer_user_details_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='details',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
