# Generated by Django 5.1.4 on 2024-12-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0007_remove_userdetails_details_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
