# Generated by Django 5.1.4 on 2024-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0008_alter_offer_options_delete_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(blank=True, help_text='Anzahl der Überarbeitungen (-1 für unendlich)', null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='Default Detail Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
