# Generated by Django 5.1.4 on 2024-12-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0011_alter_offer_min_delivery_time_alter_offer_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, null=True),
        ),
    ]
