# Generated by Django 5.1.4 on 2024-12-31 16:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0013_alter_offer_min_delivery_time_alter_offer_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_id',
            field=models.IntegerField(default=1, verbose_name=django.contrib.auth.models.User),
        ),
    ]
