# Generated by Django 5.1.4 on 2024-12-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0014_offer_created_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='created_id',
            new_name='creator_id',
        ),
    ]
