# Generated by Django 5.1.4 on 2025-01-04 20:27

import authentication_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0022_remove_ordercount_business_user_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creator_id',
            field=models.IntegerField(default=1, verbose_name=authentication_app.models.CustomUser),
        ),
    ]
