# Generated by Django 5.1.4 on 2025-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], default='customer', max_length=255),
        ),
    ]
